name: core_app
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: phamnhuvu <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  rxdart: ^0.20.0
  tuple: ^1.0.2
  web_socket_channel: 1.0.9

dev_dependencies:
  test: ^1.0.0
